### ISSUE TITLE
Understanding a Diagram Found on Twitter

### ISSUE THREAD

**Issue by abebeos** [abebeos/breeder#1]
### Original

https://twitter.com/scasplte2/status/1613243934557233161

### Tasks

- [ ] strip graphic (provide textual representation, in a html table)
- [ ] reduce complexity
- [ ] write down the goal
- [ ] write down requirements
- [ ] evolve the table

### Execution

(...)
